import 'package:flutter/material.dart';
const login = "Login";
const signup = "Signup";
const name = "name";
const email = "Email";
const pass = "Password";
const passhint = "******";
const emailhint = "email@gmail.com";
const numberhint = "+91 9512714369";
const mobile = "Mobile Number";
